amd_microcode_package: amd64-microcode
cron_package: cron
dconf_package: dconf-cli
dns_utils_package: dnsutils
intel_microcode_package: intel-microcode
lm_sensors_package: lm-sensors
nfs_client_package: nfs-common
openssh_package: openssh-server
openssh_service: ssh
python_package: python3
python_pip_package: python3-pip
rename_package: rename
sftp_path: /usr/lib/openssh/sftp-server
sudo_group: sudo
vim_package: vim

